apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
      - cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EWXdPVEEyTXpVek0xb1hEVE15TURZd05qQTJNelV6TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTm1OCmFOVytrNldWcXY3c1R2aTlxQzdRdGdHT00vMUozc3doUFJ5NnVnc3Bub1YwNVBJZjE3Y0VCSDNxTkhxYytFc0MKWXZGdFFsNENaQ1JVbGJlSTcrZnl3dWpBRXhyeDRtZzkwQXhMbThCamFxS3pqNDk5cTUrWUdJcGd1MkVYbnhldApxU0VkbVprVlBra2t5RVFtMGFTMDVUTy95ZklndWFWTlFWU1dKL3RBZHlwKzE3R292dkt0OVYvK3c1eUp6WnVkCnZRZzkwcGxmT0hkbGZKS2lxQ3R1NnlRREQwd3BySXRzNWFLMWtKU2FFWXF2NFFQRGVaRHBPYzliTVBxaFhjTVMKNk5Ic2lUK3dqdUk5T2NRUTA5a3FtVFhYTmhJYnJwQTROTFBOZDZTbFFOM2JyaTA5SVZQYTlUdm9JbnVpNzRYbgp0Z3FwMzZkK0RTRXFuVXY5UlNzQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMN3JIKysyK05xbGhTdWcvRHJVMUoyV3l5NzFNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCbTU5WSt4TG90em1FTDJpVnNYdnZuQ2NORzlkK3lJV1liNGRrQ0wwRVlYdE9PdUVzbgpsYVNmOHo3M05MNlZJYXRNSFJrdDNxdDFWTnFoQy9IZ0VtNXkzZi9ReFVub1UzLzVBcnVnNHBGUlJFazFoZFJICjUrclMxdTNuTHVCdFNFL05mUDhSMVN5eFlOQmQ1czFzaE9tcjlHeWJSNzkzVUdaV3laeUZVWGlhU0pMOVhCVC8KM3VPZUI1ZVJBNVpjVnpvdDY0N0FzUXVONWJ6a0hBeTF3N2ZJMjMvcjJ2R1dxSDUvTlBjVFhKMXpYTjc1cTEvYgp1cEtVUUQ4MTlKVGlSRUlWMzUvMTNGTnd6Tll2Rk1kVklGQjFmRDg4ZjUzZTJXUitLRU8wVmVYeVZKUlZhbkFLCkJKb0RRNGphQy9ya1RvOVFCUGRSSnJOeVJzRDhVY3RaOWxqUgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          server: https://192.168.101.47:6443
        name: cluster.local
    contexts:
      - context:
          cluster: cluster.local
          user: kubernetes-admin
        name: kubernetes-admin@cluster.local
    current-context: kubernetes-admin@cluster.local
    kind: Config
    preferences: {}
    users:
      - name: kubernetes-admin
        user:
          client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJVnFZWGY3VnJvNTR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TWpBMk1Ea3dOak0xTXpOYUZ3MHlNekEyTURrd05qTTFNemhhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdabTgyUlFGT3EzWmZMVDMKY2tWRk95V0VrOHFad3hkd2cxakZ1TGwrc09ZMTN2ODZtYkV4MjNyK3dJQk5ibkx3NFNiRCtIUTJnZlRtKzc4ZwpOZnZkSzlUcG9lckRHZTNGTEhUMTIxa0JQaGs5WXBBWFFnaThndlNYUSt2Vm5CY3ZRMmFVenVGakZ1WW9Wb1p5CmYrRGVvUkl3WUZVUjVvcHdRTmxoczFDemxQZFU5QndyYnR4Y21paDF4U3lYOWUwdHJ6aGhsanRvWUovRUVXOGIKQ1BuZ1U2L2hjb1lVUWtMcXlhTllhZjVGZFJqYVAyT1IzUkNQaVhPc1FPVlNwcDFRZFI3ZWJ4SjZuNjgrd2JVSQpqZklvcHowOFdWQTc5bTEvMEkyMDBnQTE0dTlZUDZES1dUKzZudUtiMkdNY0RkQ1Z1MjdlbVphQTRlc1NNa2lYClBaVml6d0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JTKzZ4L3Z0dmphcFlVcm9QdzYxTlNkbHNzdQo5VEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBeGNQMXh5QlRnazdGNks5TnFyYWJXY0Fvam03Uk5iQko3QlZ2CnFuTEFvUXZNYzlGRkdWcWh1VUNwcTEwVm4wWmc2Sm9NNzllM2tCd2dDOWd3Y2l5ZGFBTGh6aCttdGVhZ3JEUlUKd1BhbjBNSGpvZzZaZmF2MW1OYTlRN0loMG5Fc0NXbmRPS2ZaQlJhWFU4S0pyY1BTdmdheFE2ZjdmaHNLZUt0QQo3RjZvWXJtMDJIMEZjTnNFUGlKMHYrVzc1dG5yUmF4VjRHRW83V3VqSkFzN2ptYnY3YUFwd1g4WjliOWR2QUVsCnFCZ2lkVWNJQ2pWZ0hGcUZJUzdYOVdGSjQ4eldvVFpMTGU5cmlROTdBQWJUZkdXQVA0ZnIvKzh2RjVYRm5wUGQKTnczMVV4VDAyS2d2VlJtZ281NlRBRXlsaHB6T1dMMkkyNEFKUFVrZDRsVkpYa2NYdlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBd1ptODJSUUZPcTNaZkxUM2NrVkZPeVdFazhxWnd4ZHdnMWpGdUxsK3NPWTEzdjg2Cm1iRXgyM3Ird0lCTmJuTHc0U2JEK0hRMmdmVG0rNzhnTmZ2ZEs5VHBvZXJER2UzRkxIVDEyMWtCUGhrOVlwQVgKUWdpOGd2U1hRK3ZWbkJjdlEyYVV6dUZqRnVZb1ZvWnlmK0Rlb1JJd1lGVVI1b3B3UU5saHMxQ3psUGRVOUJ3cgpidHhjbWloMXhTeVg5ZTB0cnpoaGxqdG9ZSi9FRVc4YkNQbmdVNi9oY29ZVVFrTHF5YU5ZYWY1RmRSamFQMk9SCjNSQ1BpWE9zUU9WU3BwMVFkUjdlYnhKNm42OCt3YlVJamZJb3B6MDhXVkE3OW0xLzBJMjAwZ0ExNHU5WVA2REsKV1QrNm51S2IyR01jRGRDVnUyN2VtWmFBNGVzU01raVhQWlZpendJREFRQUJBb0lCQUE1ZG1Rekdsb2kvSTdkRQpPbVJKVFpUUStPQjZsU1JMMWZaNUhOclRNTnB4aXFmTWFvM0MvejhaQmxSRWNQcDBIdm1tQmI2bTZQQ0Z1cW9OCmlaZFg1QlovaXdLUHlBQmhpMUw4THM0aThadXBCY3dOZ3h4TVI2aXorNUYzcTNjVXBWWXNBM2pDY3JiZFJ6cjgKYVB5aU5BTGh0YU5BVEw2OW9ReSsxS2dZb2VxNHVwUUxHS3NheG55L1N1M1hpVE9nQjYzeEdlS2tnSTFXZVU0cApwYVFDUnpyVk9nU0cvSVN2S2hYem04ejlySkVGZW9rcGtJSExMekFNcHlVbDRYN0ZRRURBa2F3c0hpSTd5NmdICkhyeWhRTjhIRnRSL1VDMG8wQnhFK1hNN04rTDdtMFE1Q2dlMTJNMk1USUVuaVZJQitNSVM1M0d2c044VHhhZjAKQU13Z3FMa0NnWUVBM2pHK1pKbzRjR1Rhc3JFd3pBZWdOeVlhd2N2WFdGNFRhSkVaTFVnMUE5TE9Lekk3NXhXZQp0aTFLSk8rancwRkJxZGx0VmZCSGs5TkYzVktVc0R2MTBLT3UvT2JvT2p1eU55RVBTaDY4K1djcm9Ta3poRHdvCnZYdk8zSFk5ajN1TUFqSUNwT2VKVnFKZ3p6UDUzb1psdGRMcXVGSjdsQUZIcGxrWkh2QTVCV1VDZ1lFQTN3NUwKTllicXNoQkJUWVUrM0ZqSXRaT002MWlPdnNxSkQwdFR4OTVidU01WTV2VlRwbEpuR1l2ak1KcUxzeTBNSGpQeQpRQ3VORThIRXhzZ2wydDRjeVFza2VZWXMrUXFvY0hLbVZkamNqNStyWWRSWlU0WTBzR0FxRjYwcHQ3WnVVMFdxCmM0YXJyVmxjNVBCc3NKT2RlZkFDVzlZdUhFU1NpWUFoNXIwenJpTUNnWUVBckw0Um5sY0R2K1c0M1NuQ25TemsKazF1TmU5TkZKVTltV1dwTkg1WSttUzFmMmRkaEdPUUhFdTBjOHFCWU9lblc2ZnkrOHd3dUtiQWNaZGZZL3padQpnbmx2QnZGaDVEd2E3cDlHS3NMQStra0tjMjM3dmplakdNVlRhclNHWWJHVWhQUnFkOWdHUHhOWW5sNXpTVnhGCllObU1ZQ2JJS3FYZ0ZXUzVrZ01DNGIwQ2dZQUt5RVlhY0Vzb0VHRVh2amtyclo4R0ovdkg1S0FCMlFpSEZMMFkKREVlaXgxYkUwMWNYMHlQb3VEcGpQeFZCdEF2QjZnRHIyUzhZcFdVOXRxOGR4VjdlMlFzS1ZOSVh0OHdzbzE0bgpDRFNoUExhc0kvZXRjZTlhRjB2eG1RMUxOQ1poSUJ6OU9LVlQyOTRCc3gyTjY1VFJNQ2p0QjQxekVGMkZDQXliCmVzbmt3UUtCZ0dhYjB5bHZBd1c4MG52UytTMmJZUVFnNU8rUTl0bDFRREZMeEZhaC9GOXdydWUxSzJYQ0xJaXAKR1l3RnZSVklJTFNIL2daRG96ZktBNUFwOFJoOTQ4T2pCV2pTYXBKVmMxS1kvSkkxUXJMVnNqNXViSTVjc0dtZwpkb2N0Y2txSWw2dFRxTDkvcGpiOUllM0g2UEVtWVl5Ny8xQ1NyTERtN2J3TVIyMGhsY08wCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  otel-collector-config: |
    receivers:
      prometheus_simple:
        collection_interval: 4s
        endpoint: 192.168.101.47:31445
        metrics_path: /federate
        params:
          match[]:
            - '{job="local-cadvisor"}'
            - '{node_type="Public"}'
    processors:
      hypermonitor_relationmetricprocessor:
        rules:
          - unify_metrics:
              - container_spec_cpu_quota
              - container_cpu_usage_seconds_total
              - container_memory_rss
              - container_memory_usage_bytes
              - container_spec_memory_limit_bytes
              - io_sid_traffics
            description: unify under the deployment
      attributes:
        actions:
          - key: exported_job
            action: delete
          - key: exported_instance
            action: delete
    exporters:
      prometheusremotewrite:
        endpoint: "http://192.168.101.47:31445/api/v1/write"
        external_labels:
      otlphttp:
        endpoint: "http://192.168.101.47:4318"
        compression: none
    service:
      extensions: []
      pipelines:
        metrics:
          receivers: [prometheus_simple]
          processors: [hypermonitor_relationmetricprocessor,attributes]
          exporters: [prometheusremotewrite,otlphttp]
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  labels:
    app: hyperos-relation-metric
    component: otel-collector-hyperos-relation-conf
  name: otel-collector-hyperos-relation-conf
  namespace: default
