apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-hyperos-relation-conf
  namespace: default
  labels:
    app: hyperos-relation-metric
    component: otel-collector-hyperos-relation-conf
data:
  otel-collector-config: |
    receivers:
      prometheus_simple:
        collection_interval: 10s
        endpoint: 192.168.1.51:31445
        metrics_path: /federate
        params:
          match[]:
            - '{job="kubelet"}'
            - '{reporter_name="mlet1"}'
    processors:
      hypermonitor_relationmetricprocessor:
       rules:
        - unify_metrics:
            - container_spec_cpu_quota
            - container_cpu_usage_seconds_total
            - container_memory_rss
            - container_spec_memory_limit_bytes
            - io_sid_traffics
            description: unify under the deployment
      attributes:
        actions:
          - key: exported_job
            action: delete
          - key: exported_instance
            action: delete
    exporters:
      prometheusremotewrite:
        endpoint: "http://192.168.1.51:31445/api/v1/write"
        external_labels:
    service:
      extensions: [ ]
      pipelines:
        metrics:
          receivers: [ prometheus_simple ]
          processors: [ hypermonitor_relationmetricprocessor,attributes ]
          exporters: [ prometheusremotewrite ]
  kubeconfig: |
    apiVersion: v1
    clusters:
      - cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1URXlOVEF4TlRRME4xb1hEVE14TVRFeU16QXhOVFEwTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDFZCmNPN21ISDE5bHBjNVNFTXcxVjNIM2hvTms1cmprSEFtdWhBSG5ha3EvN1JzbUpLOWpyeWNES213MllwbzZ6NUMKRVpiREZmZmR2RVpFdUxjZGZNUTVmSm5ZM1lJd3FWOWsrdXVxdU1Dc3BLL1VZaGgzN3ZzQmVxcG5ENGlmbUtZOApxRXZsTzlkMUJFU1ZDOEZQSmtmTnRsV2czdzdqZG1GYUtZWjJOcTdIRjJTbXIxYTgrQ1JqeXNDSlBHUTJWM3dmCkwxWGtuK1JSL0E2L0p0c2RnaWwzYjJMbkRkSmROTERMckJjQVN6cHJGaXE5UnZndm04ZTJ6SEk1LytDSEVVNk4KQ2NQZjZrbWZTWEFjTXA4RjUvV2xVRkoram1VRlk3UVp4M0gxZ1E2UWR2Y2lGcGxCaWVuSyttL0ZDZDJFWW9sVgpSOVNheFZpMEYwYVVscDBzeWFjQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMSHNvQ2FESDJNOVh3NnVJNnFwTGxQSlZGRlNNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBSGVYMFN1dTRYMDZqTWJ0VDh3M3phMWlmMWtuMmZDNTlxaENNT0dLUG9lUWxBOFBmRwpmZEtrdS9keE45OHhpL0hkcCtPa0I4YmJoNWVEWmFUajRQbGd4QnpUVk1VcllxVnprMTlkVVBYWGVQNFB3eFB6CmFEdCtsUjZsUG45ZEM0UVZ0OW93cVExdFNXbVRmN1k2TUdqWWEwTTlmS1lxUWtUQVNSczVVb0U3YlM3aVZleXMKUFk4T2l4TjdReFY4Y043djBML29wSjlyTU9Pcis0MVByVysrZFk3U0dSSEJWVU5EbTlLR0hqZjhQQVk0NFF6MgpnTXJOaURnaDJlK0VLczVybC9NNEVhU2FKYkh1TkFmWkJieUt6K1RwRXdHVG45cWh2eXF4bGlBZzl5c3EzK3o1CmJvRkZKS3VKZURQQ1BtQ01ESDAyQUZKM0RKOGprcCtTdXlucAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          server: https://192.168.1.51:6443
        name: cluster.local
    contexts:
      - context:
          cluster: cluster.local
          user: kubernetes-admin
        name: kubernetes-admin@cluster.local
    current-context: kubernetes-admin@cluster.local
    kind: Config
    preferences: {}
    users:
      - name: kubernetes-admin
        user:
          client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJUitOWjduOHNTcVF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TVRFeE1qVXdNVFUwTkRkYUZ3MHlNakV4TWpVd01UVTBORGxhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXFxaXl5NVpBWGlWcG1iOWIKSjRnTXlFNGlTK09MKyt5VmhsMVl2dDNKZVl1TnJNdjJRdEtTWS9IL2J5VVRuUGtIL3g4VVcyZHVZUmpFd3JWQgpqS0xXYXNQSnQwQ1c0YjBUeWtieXlud3R3RlRJYmcvalRKQnJtWXpEK2tSZGorcW9hQ3ZWdW9DbFl6ZDNJVzlSClJwOTFSa2dicXFTbmI3bW91VUFvZ0lNV2J6WCtxU09odjlWTjU3Vm40R0Z2d0VUS3JBT2tBYkhvUDFHZ081N0cKR01NT1Q0N0lGQ055QTJNNkZ6QnZFcmdmZUNDL0tyNWxxU21yYkNwMk1oc1NFU3AyM25ZaUhJK0JQang4QU0wMApwenJ3djlvTTBEc3p0eWFMcEVKWldPbnA0bUhMbEZTN3JPaWlaVWNDbWJyQ3RkRG0zWkZ5YVBVRXc0Mnl6U1E3ClVBSjh3UUlEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JTeDdLQW1neDlqUFY4T3JpT3FxUzVUeVZSUgpVakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBRzh6VnBteG00ZmFuTmhsMmtpWHZMWXFIbzduZXpOZXJ5cHJBCi9oNjdRRjF1elhsWWN3MkFjRnI2ZlFvcVBnYUxwMTY2ZlNjTDhPRVI5N1FzWXd3bnVIY20zQlFRZE83YTdrVUsKdnFZNmRQRXJrUzBzbUV4bnVIcnVMaHVhaWJRMzN3RzJlMTJJd2VENlRvQ25CNTQyWFBnODNqb1BGcmZ0MXltUQpwYVcycHk1eUhRMG5ORnNKY3FaanJvRjM0TEt5SnZrcktPWmVsMFBpZXprYmZHV0FBZTFZT2JobTEraFR5MGZkClpsTVlmZkV6R2FpaWtJSitSS0Z0V0YwaXJ0MkVyeWVYWkFuOWZ4TERUTHljQ1NGVnRCcnRBSVQrTzVLL1E0RFAKcmxhOTVxV0w5ZmVUWDFCcTdxRVNkOUMzOE1vZ25wWGRwSm40LzNXOXlESnRteXhzMXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcXFpeXk1WkFYaVZwbWI5Yko0Z015RTRpUytPTCsreVZobDFZdnQzSmVZdU5yTXYyClF0S1NZL0gvYnlVVG5Qa0gveDhVVzJkdVlSakV3clZCaktMV2FzUEp0MENXNGIwVHlrYnl5bnd0d0ZUSWJnL2oKVEpCcm1ZekQra1Jkaitxb2FDdlZ1b0NsWXpkM0lXOVJScDkxUmtnYnFxU25iN21vdVVBb2dJTVdielgrcVNPaAp2OVZONTdWbjRHRnZ3RVRLckFPa0FiSG9QMUdnTzU3R0dNTU9UNDdJRkNOeUEyTTZGekJ2RXJnZmVDQy9LcjVsCnFTbXJiQ3AyTWhzU0VTcDIzbllpSEkrQlBqeDhBTTAwcHpyd3Y5b00wRHN6dHlhTHBFSlpXT25wNG1ITGxGUzcKck9paVpVY0NtYnJDdGREbTNaRnlhUFVFdzQyeXpTUTdVQUo4d1FJREFRQUJBb0lCQVFDT3FuYkYwVGJBUGFCNQpJa3BPMHVKMHRUVGdvam9OQWF2Q1p0amd2c0pHTk03Y1RLbnpGTnZDWjdUMU1sYWlIR0Y5K25wbkt5RlFWSWR3CmlseGcrR1F0WHIyTHo1Z1M0S0Roc2N3WVVCVmpPcjFQblVLVWFBczdrenptUkM2L09CbE85STQ0Mm9Eb1g1N2MKdVpXRlo1cC9oWnB6WGpDSEt2c00yc0RCSmxVajQrNnYwOG80SC9ud2pLUXQ5cFVscXAxeWkwRFN4YThMZWs0UQppOVUzMjB3RFY0UE9UbmJkdFdxNENqQVFET2pabzVZd081bEdodnMvMSthZGFXUHNEU2FkNUErRnZCUG8zRkFaCjZhSUhOZGlqM3lYd0QwMzByRGZWY3ZxdUF6d25peXM0dCtEVnZhUlp5ZHNHalhmTXJ5QUxXSUpTZU1LUHRHTmgKZEdaenpkOU5Bb0dCQU1hRThvQjhVeHBwbWNuVUI3QmRpWTlCbHcySzNqUlJXQ2FMNWJtVkRwVk05Y0grbUxEMApiWnlQNVNaaXRPTkdBTXRZUHVSNGw0cm9BWVhNeURFSmljblhOTUJ5UGVKRTVrQ25WcDNSc0RnN2lQem5NaS9YCkM1czQxNE5BODBiSks4dHRudUFaUUFNN3pFR0JiM0F2QzZSL3krTnZKcVRtR3hYbDNNcHUxUnJYQW9HQkFOd1MKb1VFaHF4MVBJc0lwQnhhTEZLdXJwcVgxWWhIYWhVclEyMllJellFd1g0YTJwT0g3SnBud0ViUFc1Z05OeDdjUApZUC9RSSt0TTVDYWt5WnY1dGxFQ2c2RFhJdEVhTkFKMFR3M2puSjRnaWIzL2Q2bklSaUZ6Z0hxNFcxNSs3R21KCjJxRDZuanZvajhFRjNPOHFyRktYbVFVN0tYamR2TlpncmhOd21Rb25Bb0dBZmlkWUw3eFIxelFLVGM3WEFBWEEKOSs5M2ZWeWxMbHdQQjVmWmFhREdmcXhFZEg1RkxCWjRYWWkzMXpmY3VaenZ2a2thMW5lbjNkYm51TTVVM1l5eApLam4vUk5pVWFPamQ1WEl4d2VMUitEb2xLSW9IUTQyRnk2TkltUms2UDk1eFhUb1JQMW5zYXVHaVFISnZqYnZuCnl5YUhPOFdUcWpDc1A3TXVKdHBkeEVzQ2dZQStkSThNOCtnaTlqMXdDc0szTkJ0V3FPMHZkaGN4NStraUZXbmUKYUNzaU9iOHlkUTBRRVAyZ2ZGQVowS2dRVWZlV3pTZURFZWZQdEUrZlkrN1BkQ3U0aTlVZFJWRGROT21EdE14bQpyYXpaOTNQLzFzdDRCSjFhaXZQd1gvZVdOc0VUSm90RVdqdWoxdGxOTjBPL0lFWXRYbGFQOUgxTmp1Z3prdFowCkwrVk95d0tCZ0dxd281VVBoTmVGWHVWREZOdTc1dUs1QmRXcHRZMnZZT1hGcHVPVGJHOXluSzUza2loUHpJTngKaXFJUjg4WFBGRGc4UjRxUEVNcXJoREN3WXNtb1ZVVy9XV2tFTmZCdjB5SnNhTGpKdTROQ0w3aXNZVWZsNEZvYgptM3gyYWZyLy9qV2JNQ0Fxd2dHYUpqU2s2QTN5N2x3N29SdEJqNkY0dHVIbmtOTzZQT1U0Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==